http://localhost:3000/courses

###

GET http://localhost:3000/courses/1

###

POST http://localhost:3000/courses HTTP/1.1
content-type: application/json

{
  "name": "teste"
}

###

PUT http://localhost:3000/courses/2 HTTP/1.1
content-type: application/json

{
  "name": "Java"
}

###

DELETE http://localhost:3000/courses/3
